api_platform:
    title: 'ByMia REST API'
    description: 'Documentación de la API que utiliza el frontend de bymia, la plataforma 3PL y el CRM'
    version: '0.1.0'

    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]

    formats:
        json:
            mime_types: ['application/json']
        jsonld:
            mime_types: ['application/ld+json']
        html:
            mime_types: ['text/html']
        multipart:
            mime_types: ['multipart/form-data']