api_platform:
    title: 'ByMia REST API'
    description: 'Documentación de la API que utiliza el frontend de bymia, la plataforma 3PL y el CRM'
    version: '0.1.0'

    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]

        # api_keys: ESTO SIRVE PARA HACER LA VALIDACION DE USUARIOS CON API KEYS
        api_keys:
            apiKey:
                name: Authorization
                type: header

                
    # show_webby: false ESTO QUITA LA ARAÑITA DE API-PLATFORM 
    show_webby: false 