security:
    enable_authenticator_manager: false

    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: "auto"
        App\Entity\User: "auto"

    providers:
        users:
            entity:
                class: 'App\Entity\User'
                property: "email"

        api_client:
            entity:
                class: 'App\Entity\ApiClients'
                property: "api_client_id"

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/*
            lazy: true
            provider: users
            anonymous: true
            form_login:
                check_path: app_security_login
                login_path: app_security_login
                default_target_path: app_homepage
                csrf_token_generator: security.csrf.token_manager
                use_referer: true
            logout:
                path: app_security_logout
                target: app_security_login
                
    access_control:
        - { path: ^/security/*, roles: PUBLIC_ACCESS }
        - { path: ^/reset-password/*, roles: PUBLIC_ACCESS }
        - {
              path: ^/secure/*,
              roles:
                  [
                      ROLE_SUPER_ADMIN,
                      ROLE_TEAM_GERENCIA,
                      ROLE_TEAM_CATALOGO,
                      ROLE_TEAM_OPERACIONES,
                      ROLE_TEAM_FACTURACION_Y_COBRANZA,
                      ROLE_TEAM_LOGISTICA,
                      ROLE_TEAM_ATENCION_AL_CLIENTE_POSTVENTA,
                      ROLE_TEAM_MARKETING,
                      ROLE_TEAM_DISENO,
                      ROLE_TEAM_SOCIAL_MEDIA,
                      ROLE_TEAM_DESARROLLO,
                      ROLE_TEAM_ANALYTICS_SEO_SEM,
                  ],
          }