controllers:
    resource: ../../src/Controller/
    type: annotation

secure_controllers:
    resource: ../../src/Controller/Secure/
    type: annotation
    prefix: /secure

api_controllers:
    resource: ../../src/Api/
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation
