<?php

namespace App\Constants;

class Constants
{
    // EMAIL TYPES

    const EMAIL_TYPE_VALIDATION = 1;
    const EMAIL_TYPE_WELCOME = 2;
    const EMAIL_TYPE_FORGET_PASSWORD = 3;
    const EMAIL_TYPE_PASSWORD_CHANGE_REQUEST = 4;
    const EMAIL_TYPE_PASSWORD_CHANGE_SUCCESSFUL = 5;

    // END EMAIL TYPES

    // STATUS EMAIL

    const EMAIL_STATUS_PENDING = 1;
    const EMAIL_STATUS_ERROR = 2;
    const EMAIL_STATUS_SENT = 3;
    const EMAIL_STATUS_CANCELED = 4;

    // END STATUS EMAIL

    // STATUS CUSTOMER

    const CUSTOMER_STATUS_PENDING = 1;
    const CUSTOMER_STATUS_VALIDATED = 2;
    const CUSTOMER_STATUS_DISABLED = 3;

    // END STATUS CUSTOMER


    // STATUS COMMUNICATION BETWEN PLATFORMS

    const CBP_STATUS_PENDING = 1;
    const CBP_STATUS_ERROR = 2;
    const CBP_STATUS_SENT = 3;

    // END COMMUNICATION BETWEN PLATFORMS


    //REGISTRATION TYPE
    
    const REGISTRATION_TYPE_WEB = 1;
    const REGISTRATION_TYPE_BACKEND = 2;
    const REGISTRATION_TYPE_IMPORT = 3;

    // END REGISTRATION TYPE

}
